In [43]:
# Example explaining how to extract feature set from a set of text documents
# Making DataFrame of the entire dataset feature and their labels
# Usage of train-test split framework 
# Training Multinomial Bayes Theorem to train the machine and test in the test set. 

import sklearn
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
corpus = [ 'As great game',
'The election was over',
'Very clean match',
'The election was as close as game',
'The match was over']
vectorizer = CountVectorizer()
#print(type(vectorizer)) # <class 'sklearn.feature_extraction.text.CountVectorizer'>
X = vectorizer.fit_transform(corpus) #Learn the vocabulary dictionary and return term-document matrix.
columns = vectorizer.get_feature_names() #names of the features, Array mapping from feature integer indices to feature name
#print(vectorizer.get_stop_words()) # no stop words by default, a is not taken because of token_pattern argument
data = X.toarray() # a numpy array, <class 'numpy.ndarray'>
#print(type(data))
df = pd.DataFrame(data=data, columns=columns)
print(df)
X_train, X_test, y_train, y_test = train_test_split(data,['Sports', 'N Sports', 'Sports','N Sports', 'Sports'] , test_size=0.20)
print("X_train")
print(X_train)
print("X_test")
print(X_test)
print("y_train")
print(y_train)
print("y_test")
print(y_test)
clf = MultinomialNB()
clf.fit(X_train, y_train)
print("prediction")
print(clf.predict(X_test))


   as  clean  close  election  game  great  match  over  the  very  was
0   1      0      0         0     1      1      0     0    0     0    0
1   0      0      0         1     0      0      0     1    1     0    1
2   0      1      0         0     0      0      1     0    0     1    0
3   2      0      1         1     1      0      0     0    1     0    1
4   0      0      0         0     0      0      1     1    1     0    1
X_train
[[0 1 0 0 0 0 1 0 0 1 0]
 [1 0 0 0 1 1 0 0 0 0 0]
 [2 0 1 1 1 0 0 0 1 0 1]
 [0 0 0 0 0 0 1 1 1 0 1]]
X_test
[[0 0 0 1 0 0 0 1 1 0 1]]
y_train
['Sports', 'Sports', 'N Sports', 'Sports']
y_test
['N Sports']
prediction
['Sports']
